### ISSUE TITLE
`wick registry push` should add `latest` tag in addition to version tag by default

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#235]
**Is your feature request related to a problem? Please describe.**
To support the `latest` tag structure, we need to push the latest tag in addition to the version tag.

**Propose a solution**
add an option `--latest true` that is enabled by default so every `wick registry push` is pushed using both the version and the latest tag.  It can be disabled by passing `--latest false`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsoverson** [comment]
`:latest` shouldn't be added by default assuming that `latest` is considered the tip of development or the bleeding edge.

Pushing a patch or minor version (i.e. `mypackage:0.9.1`) when the next significant version is higher (e.g. `mypackage:2.1.0`) wouldn't produce the expected behavior.

I'll add a command line tag to make it easier though.
