### ISSUE TITLE
Tracing errors on success

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#317]
**Describe the bug**
I run my application with `--trace` flag and it immediately stops execution after sending one trace span. 

**To Reproduce**
I have env variable set:
`export OTLP_ENDPOINT=http://127.0.0.1:4317` and I added the 

**Expected behavior**
The app should run as expected

**Actual behavior**
The app stops execution after sending the first trace (successfully).

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**

**Comment by jsoverson** [comment]
This may be partially fixed by #319. I had to disable the scoped logger implementation when I encountered this issue. It seemed to fix a slew of unpredictable behavior. The only effect is that the first few log entries related to parsing the settings file are dropped.

Closing this because it appears fixed, but reopen if you still encounter it.
